### ISSUE TITLE
subida de modulo

### ISSUE THREAD

**Issue by cgermanb** [kazeno/Oca-ePak#1]
Buenas! te cuento que al querer subir el modulo en 1.7 arroja error y no lo sube, 
a lo mejor no lo descargue correctamente, directamente clickee en clonar y me descargo el zip, habra que hacer algo mas?

Saludos

**Comment by kazeno** [comment]
Hola, necesitas descargarlo desde los releases: https://github.com/kazeno/Oca-ePak/releases
