### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lat' of undefined

### ISSUE THREAD

**Issue by z72diego** [kazeno/Oca-ePak#2]
Hola Kazeno buenas tardes, gracias por desarrollar y compartir públicamente el módulo, está increíble.

Hay un error que se da en el checkout, cuando se selecciona un medio de envío distinto a E-PAK con selección de sucursal y luego se lo vuelve a seleccionar:

```
Uncaught TypeError: Cannot read property 'lat' of undefined
    at HTMLInputElement.carrier_selection (bottom-bc3142161.js:652)
    at HTMLInputElement.dispatch (bottom-bc3142161.js:39)
    at HTMLInputElement.g.handle (bottom-bc3142161.js:39)
carrier_selection @ bottom-bc3142161.js:652
dispatch @ bottom-bc3142161.js:39
g.handle @ bottom-bc3142161.js:39
```

Alguna sugerencia? Saludos!

**Comment by kazeno** [comment]
Hola @z72diego , en que version de Prestashop pasa eso? Y podrias por favor describir mas a detalle los pasos exactos para replicar el problema?

**Comment by z72diego** [comment]
Hola @kazeno! Sucede en PS 1.7.6.1, podes chequearlo rápidamente en el checkout de la siguiente tienda: https://theway.com.ar/
