### ISSUE TITLE
error en prestashop 1.7.7

### ISSUE THREAD

**Issue by shacker2** [kazeno/Oca-ePak#5]
Hola. en presta 1.7.7 cambiaron los hooks y no funciona. tenes alguna idea?

**Comment by gvaianella** [comment]
Hola. Estoy con el mismo problema desde hace bastante. Hoy me puse a revisar el código a ver si puedo encontrarle la vuelta, porque creo que este código ya no está siendo mantenido por @kazeno.

**Comment by kazeno** [comment]
Hola, si lo sigo manteniendo, pero mi disponibilidad de tiempo es bastante limitada por el momento, además de que ya no tengo acceso a una cuenta activa de OCA para realizar pruebas que requieran el webservice. Agradecería información más específica en cuanto a qué es lo que está fallando, sobre todo si se trata de cambios en hooks, para poder agilizar el proceso.

Saludos!

**Comment by gvaianella** [comment]
Hola, @kazeno. Pensé que no lo mantenías más. Me alegro que no sea así.
De repente, el módulo no funciona a nivel backoffice. Es decir, las compras se registran sin problemas, pero no puede generarse la etiqueta. No estoy seguro de que haya sido por cambios en el hook, pero todavía no termino de saber a qué se debe.
Estoy tratando de hacer algunas pruebas (me gustaría poder darte una mano con un pull request) pero por el momento el error que obtengo es que el XML que se envía es incorrecto.
¿Vos tendrás disponible alguna documentación de la API, o sabés si hay algún lugar que la tenga actualizada?

¡Saludos!

**Comment by gvaianella** [comment]
Hola, @kazeno.

Efectivamente, se debía a un cambio en el hook, que parece no estar documentado. 
El params que recibe hookDisplayAdminOrder solo contiene id_order, por lo que las primeras líneas de la función deberían ser así (no tengo permisos para pushear un branch y hacer un pull request, perdón):

```
    public function hookDisplayAdminOrder($params)
    {
        $order = new Order($params['id_order']);
        $carrier = new Carrier($order->id_carrier);
        $op = OcaEpakOperative::getByFieldId('carrier_reference', $carrier->id_reference);
        if (!$op)
            return NULL;
        $address = new Address($order->id_address_delivery);
        $carrier = new Carrier($order->id_carrier);
        $customer = new Customer($order->id_customer);
        if (in_array($op->type, array('PaS', 'SaS'))) {
            $relayId = OcaEpakRelay::getByCartId($order->id_cart)->distribution_center_id;
```

Con este fix al menos se pueden generar etiquetas. No es posible verlas (hay que ir al sistema de OCA) y el formulario se ve mal, pero ya voy a revisar eso después.

@shacker2, quizás te sirva esto por el momento.

**Comment by shacker2** [comment]
Hola. gracias. Tambien hay un error que hace que en ps 1.7.7 no funione el  override ya que tiene un parametro mas

agregar en el override classes/cart.php esta linea  $id_zone = null, bool $keepOrderPrices = false:


   public function getPackageShippingCost(
        $id_carrier = null,
        $use_tax = true,
        Country $default_country = null,
        $product_list = null,
        $id_zone = null, bool $keepOrderPrices = false
    )

**Comment by shacker2** [comment]
Tambien que no aparezca el template es por que en prestashop 1.7.7 se usa el nuevo theme en admin. para que puedas ver en el detalle de pedido el modulo de oca, tenes que copiar del theme por defecto

admin/themes/default/template/helpers

a

admin/themes/new-theme/template/helpers

**Comment by shacker2** [comment]
Con los cambios que les pase deberia funcionar

**Comment by AnibalAxA** [comment]
> Hola. gracias. Tambien hay un error que hace que en ps 1.7.7 no funione el override ya que tiene un parametro mas
> 
> agregar en el override classes/cart.php esta linea $id_zone = null, bool $keepOrderPrices = false:
> 
> función pública getPackageShippingCost (
> $ id_carrier = null,
> $ use_tax = true,
> Country $ default_country = null,
> $ product_list = null,
> $ id_zone = null, bool $ keepOrderPrices = false
> )

No encuentro el archivo a modificar.
Agradeceria mas info
Gracias

**Comment by shacker2** [comment]
eso esta en el override, classes / cart.php

**Comment by minimamente** [comment]
hola, tengo el mismo problema con el tema de generar las etiquetas en 1.6.3, venía funcionando bien.
Me podrían comentar si esta solución que detalla @shacker2 es factible para mi versión o les parece que puede ir por otro lado?
desde ya muchas gracias!

**Comment by shacker2** [comment]
en 1.6. n ose da el error, debe ser otra cosa

**Comment by minimamente** [comment]
> 
> 
> en 1.6. n ose da el error, debe ser otra cosa

Gracias @shacker2 , error de tipeo, mi versión es 1.7.6.3

**Comment by kazeno** [comment]
Agregué un pre-release de la versión 2.1 del módulo que debería arreglar varios de los problemas con versiones superiores a 1.7.6 de Presta. Si siguen teniendo errores ya con él por favor agreguen otro issue con los detalles.
