### ISSUE TITLE
Error generando órden de OCA

### ISSUE THREAD

**Issue by minimamente** [kazeno/Oca-ePak#6]
hola @kazeno
Mi version de prestashop es 1.7.3 y hace poco el modulo comenzó a tirar el error "Error generando órden de OCA". Me podrias dar una mano para resolverlo? 
Muchas gracias

**Comment by kazeno** [comment]
Hola, lo primero por revisar sería los logs de error tanto de tu servidor (PHP y Apache) como la consola de javascript a la hora de que te tira el error, para ver si hay registros de errores relacionados con el módulo.

Para debugear el webservice tambien puedes activar el modo de debug del módulo, cambiando a `true` la constante `OcaEpak::LOG_DEBUG` dentro del archivo modules/ocaepak/ocaepak.php. Esto hará que se registren logs detallados dentro de la carpeta modules/ocaepak/logs que podrían ayudar a ver que está pasando durante las llamadas al webservice.

**Comment by minimamente** [comment]
Gracias @kazeno
Se solucionó solo, era un problema del sistema de OCA, resulta ser que venció las operativas y por eso no funcionaban. Ahora que están renovadas ya verifique que están funcionando, genere una orden desde la tienda y la generó correctamente.
No sabía que tenía vencimiento y que tampoco nos iban a avisar que se venció y que no funcionan.
mil gracias por tu ayuda!
